Dialyzer warn unknown
inaka/katana-test pull request #39
Opened 2017-03-07 20:48 UTC by lucafavatella

2017-03-07 20:48 UTC, elvisci commented on src/ktn_meta_SUITE.erl
> +      undefined -> [error_handling, race_conditions, unmatched_returns, unknown];
Line 60 is too long:       undefined -> [error_handling, race_conditions, unmatched_returns, unknown];.

2017-03-07 20:48 UTC, lucafavatella commented
From https://github.com/inaka/sumo_rest/pull/73#issuecomment-284850381

2017-03-07 20:49 UTC, lucafavatella commented on src/ktn_meta_SUITE.erl
> +      undefined -> [error_handling, race_conditions, unmatched_returns, unknown];
ok, changing this...

2017-03-07 20:53 UTC, lucafavatella commented
Changed line length and force-pushed.

@elbrujohalcon It is all yours now.

2017-03-08 19:06 UTC, elbrujohalcon requested changes

2017-03-08 19:06 UTC, elbrujohalcon commented on src/ktn_meta_SUITE.erl
> +      undefined -> [error_handling
If you're gonna use ROK-style, you have to add a space after [ here

2017-03-08 19:06 UTC, elbrujohalcon commented on src/ktn_meta_SUITE.erl
> +                   , unknown];
In ROK-style, the last ] goes below the commas in the next row.

2017-03-09 11:17 UTC, lucafavatella commented on src/ktn_meta_SUITE.erl
> +      undefined -> [error_handling
addressed in force-pushed commit

2017-03-09 11:18 UTC, lucafavatella commented
@elbrujohalcon Shall be ok now.

2017-03-09 12:30 UTC, elbrujohalcon approved these changes

2017-03-09 12:31 UTC, merged